const HomeActions = require('../actions/home.actions')
const LoginActions = require('../actions/login.actions')
const CartActions = require('../actions/cart.actions')
const CheckoutActions = require('../actions/checkout.actions')

const homeActions = new HomeActions()
const loginActions = new LoginActions()
const cartActions = new CartActions()
const checkoutActions = new CheckoutActions()

describe ('Checkout', () => {
    it ('Should complete the checkout flow', async function() {
        await homeActions.navigate()
        await homeActions.clickLoginButton()
        await loginActions.fillLoginForm('juapiero@gmail.com', 'DemoTest123')
        //Search for a product
        await homeActions.search("serum")
        let price = await homeActions.getFirstProductDiscountPrince()
        let productName = await homeActions.getFirstProductName()
        await homeActions.addProductToCartFromQuickSearch()
        await expect(await homeActions.shoppingCartModalTitle).toBeDisplayed()
        await expect(await homeActions.shoppingCartViewCartButton).toBeDisplayed()
        await homeActions.clickShoppingCartViewCartButton()
        await cartActions.closeShippingNotice()
        await expect(cartActions.productName).toHaveText(productName)
        await expect(cartActions.productSalePrice).toHaveText(price)
        await cartActions.clickCheckoutButton()
        await checkoutActions.clickContinueButton()
        await checkoutActions.clickContinueWithoutReferralButton()
        await checkoutActions.fillShippingAddressForm('Juan', 'Piedra', '301 7th Ave', '', 'Ashville', 'Alabama', '35953-3317')
        await checkoutActions.clickContinueShippingMethodButton()
        await checkoutActions.fillCreditCardForm('Juan', 'Piedra', '1111222233334444', '12', '2024', '123')
    })
})